name: Integration Test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update action.yml to build locally
        run: |
          sed -i 's/.*image\:.*/  image\: \"Dockerfile\"/' action.yml
          cat action.yml
      - name: Self test
        id: selftest
        uses: ./
        with:
          include: "src/**"
          find: "ZBUFFERX_PROG1"
          replace: "ZTRAFFIC_PROG1"
      - name: Check outputs and modified files
        run: |
          test "${{ steps.selftest.outputs.modifiedFiles }}" != "0"
          grep "ZTRAFFIC_PROG1" src/zbufferx_prog1.prog.xml
          
