name: My Workflow
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: atikdevran/zbufferx_repo@v2
        with:
          find: "ZBUFFERX"
          replace: "ZTRAFFIC"
          regex: false
