name: My Workflow
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Find and Replace      
      - uses: ./.src@v1.4.4
        with:
          find: "ZBUFFERX"
          replace: "ZTRAFFIC"
          regex: false
